---
title: "week 6 section"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(sf)
library(terra)
library(tmap)
```

```{r}
# Set directory for folder
pre_fire_dir <- here::here("data", "LC80340322016189-SC20170128091153")

# Create a list of all images that have the extension .tif and contain the word band
pre_fire_bands <- list.files(pre_fire_dir,
                             pattern = glob2rx("*band*.tif$"),
                             full.names = TRUE)
# Create a raster stack
pre_fire_rast <- rast(pre_fire_bands)

# Read mask raster
pre_mask <- rast(here::here("data", "LC80340322016189-SC20170128091153", "LC80340322016189LGN00_cfmask_crop.tif"))
```

```{r}
# Set directory for folder
post_fire_dir <- here::here("data", "LC80340322016205-SC20170127160728")

# Create a list of all images that have the extension .tif and contain the word band
post_fire_bands <- list.files(post_fire_dir,
                             pattern = glob2rx("*band*.tif$"),
                             full.names = TRUE)
# Create a raster stack
post_fire_rast <- rast(post_fire_bands)

# Read mask raster
post_mask <- rast(here::here("data", "LC80340322016189-SC20170128091153", "LC80340322016189LGN00_cfmask_crop.tif"))
```

```{r}
nbr_fun <- function(nir, swir2){
    (nir - swir2)/(nir + swir2)
}
```

```{r}
bands <- c("Aerosol", "Blue", "Green", "Red", "NIR", "SWIR1", "SWIR2")
names(pre_fire_rast) <- bands
names(post_fire_rast) <- bands

```

```{r}
pre_mask[pre_mask > 0] <- NA
post_mask[post_mask > 0] <- NA

pre_fire_rast <- mask(pre_fire_rast, mask = pre_mask)
post_fire_rast <- mask(post_fire_rast, mask = post_mask)
```

```{r}
plot(pre_fire_rast, colNA = "black")
plot(post_fire_rast, colNA = "white")
```

```{r}
# true color composite
plotRGB(pre_fire_rast, r = 4, g = 3, b = 2, stretch = 'lin', colNA = "black")
plotRGB(post_fire_rast, r = 4, g = 3, b = 2, stretch = 'lin', colNA = "black")
```

```{r}
# false color composite
# Map the SWIR2 band to the red channel, NIR to green, and green to blue
plotRGB(pre_fire_rast, r = 'SWIR2', g = 'NIR', b = 'Green', stretch = 'lin', colNA = "black")

plotRGB(post_fire_rast, r = 'SWIR2', g = 'NIR', b = 'Green', stretch = 'hist', colNA = "black")

```

```{r}
pre_fire_nbr <- terra::lapp(pre_fire_rast[[c("NIR", "SWIR2")]],
                         fun = nbr_fun)

post_fire_nbr <- terra::lapp(post_fire_rast[[c("NIR", "SWIR2")]],
                         fun = nbr_fun)


plot(pre_fire_nbr, main = "Cold Springs Pre-Fire NBR", colNA = "black")

plot(post_fire_nbr, main = "Cold Springs Post-Fire NBR", colNA = "black")
```

```{r}
diff_nbr <- pre_fire_nbr - post_fire_nbr

plot(diff_nbr)

```

